# Generated by Django 2.2.3 on 2019-08-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favurite',
            field=models.BooleanField(default=False),
        ),
    ]
